services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: [.env]
    volumes: [".:/app"]
    ports:
      - "8000:8000"
    networks: [app-net]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - VITE_DEV_SERVER_HOST=0.0.0.0
      - VITE_API_TARGET=http://backend:8000
    volumes: [".:/app"]
    ports:
      - "3000:3000"
    depends_on: [backend]
    networks: [app-net]

networks:
  app-net: {}
